### ISSUE TITLE
New Video/Image Source

### ISSUE THREAD

**Issue by veyakup** [SamurAIGPT/Text-To-Video-AI#4]
Hello, the software looks pretty good but I get the error below. I think it's caused by Pexels. Is it possible to generate images by connecting to the stable diffusion API without using Pexels?

`Text ```json [ [[0.0, 2.88], ["fascinating facts", "beer text", "video start"]], [[2.88, 4.22], ["oldest beverages", "ancient drinks", "beer history"]], [[4.22, 6.96], ["dating back", "7000 BC", "ancient Iran"]], [[6.96, 10.3], ["world's strongest beer", "Brewmeister brand", "Snake Venom"]], [[10.3, 13.87], ["67.5% alcohol", "strong beer", "high volume"]], [[13.87, 17.52], ["ancient Egyptians", "built pyramids", "diet of bread"]], [[17.52, 20.34], ["workers beer", "four litres", "per day"]], [[20.34, 24.48], ["Middle Ages", "beer consumed", "water safer"]], [[24.48, 28.26], ["world record", "beer speed", "drinking"]], [[28.26, 30.64], ["1.3 seconds", "Stephen Petrosino", "1977"]], [[30.64, 34.76], ["Sumerian poem", "honoring Ninkasi", "5000 years old"]], [[34.76, 38.08], ["goddess brewing", "oldest recipe", "beer history"]], [[38.08, 41.88], ["Amsterdam cleaning", "beer payment", "five cans"]], [[41.88, 44.22], ["cleaning squads", "paid in beer", "five cans"]] ] ```
Expecting value: line 1 column 1 (char 0)
error in response Expecting ',' delimiter: line 1 column 225 (char 224)
None
No background video
Traceback (most recent call last):
  File "D:\AI\Text-To-Video-AI\app.py", line 42, in <module>
    background_video_urls = merge_empty_intervals(background_video_urls)
  File "D:\AI\Text-To-Video-AI\utility\video\video_search_query_generator.py", line 83, in merge_empty_intervals
    while i < len(segments):
TypeError: object of type 'NoneType' has no len()`

**Comment by Anil-matcha** [comment]
Yes, the working will be similar. Just replace the pexels api with any other api of your choice

**Comment by woobin3069** [comment]
I'm having the same error. Did you find a solution for this issue? That would be really helpful

**Comment by krishnacck** [comment]
Can you please recommend any alternative API provider instead of Pexels API?

**Comment by Anil-matcha** [comment]
@krishnacck Any issue you are facing with Pexels ?

**Comment by krishnacck** [comment]
yes, I am also facing same issue mentioned above.. looking alternatives...

**Comment by Anil-matcha** [comment]
Fixed with https://github.com/SamurAIGPT/Text-To-Video-AI/commit/5e45fadc04619b1cfa338f7279fc1710f867083f
