### ISSUE TITLE
Pexel api error 403

### ISSUE THREAD

**Issue by Asilomare** [SamurAIGPT/Text-To-Video-AI#5]
Was getting an error when requesting pexel's api, fixed by adding "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" to request headers in background_video_generator.search_videos

**Comment by Anil-matcha** [comment]
Care to create a pull request ? @Asilomare

**Comment by Asilomare** [comment]
Sure

**Comment by Anil-matcha** [comment]
Fixed now
